### ISSUE TITLE
offline content not loading

### ISSUE THREAD

**Issue by laureliza** [austinwritescode/opentrail.org#1]
![Screenshot_20230302-190402](https://user-images.githubusercontent.com/126834162/222595430-86126f4f-3a7d-48b5-9bc1-275e0893e750.png)

App loaded great, install on Android had no issues but the download of the offline content is stuck at 0%. Tried multiple times as well. Downloading it in the browser (Firefox) worked perfectly.

Pixel 6 with Android 13

**Comment by austinwritescode** [comment]
Interesting, thanks for reporting. This is probably an issue with background fetch, which is a pretty new feature (only Chrome, Firefox doesn't support it) so I shouldn't be surprised. If other people have this issue too it would be good to figure out why but I think for now I'll change this so Chrome users will be presented an option to download via foreground or background so at least there's a workaround.
